version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: lift_trckr_db
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
