name: Necesarry setup
description: "Sets up the environment for the other actions to run"
runs:
    using: "composite"
    steps:
        - name: Setup pnpm
          # shell: bash
          uses: pnpm/action-setup@v3
          with:
              version: 8

        # - name: Setup Node.js
        #   shell: bash
        #   uses: actions/setup-node@v4
        #   with:
        #       node-version: "20"
        #       cache: "pnpm"
        #       cache-dependency-path: "**/pnpm-lock.yaml"

        # - name: Install dependencies
        #   shell: bash
        #   run: pnpm install
