name: Build, Test, and Deploy
# activate jobs manually

on:
    push:
    #     branches:
    #         - main
    # workflow_dispatch:

jobs:
    install:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"
                  cache-dependency-path: "**/pnpm-lock.yaml"

            - name: Install dependencies
              run: pnpm install

            - name: list files
              run: find ./ -maxdepth 2 -mindepth 1

            - name: saves artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: nodes_modules
                  path: nodes_modules

    build:
        runs-on: ubuntu-latest
        needs: install

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: download artifacts
              uses: actions/download-artifact@v4
              with:
                  name: nodes_modules
                  path: nodes_modules

            - name: Build
              run: pnpm build

    # test:
    #     runs-on: ubuntu-latest
    #     needs: install

    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v4

    #         - name: Setup Node.js
    #           uses: actions/setup-node@v4
    #           with:
    #               node-version: "20"

    #         - name: Test
    #           run: pnpm test

    # todo add saving report

    check:
        runs-on: ubuntu-latest
        needs: install

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            # - name: Setup Node.js
            #   uses: actions/setup-node@v4
            #   with:
            #       node-version: "20"

            - name: Check TypeScript
              run: pnpm check

    lint:
        runs-on: ubuntu-latest
        needs: install

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            # - name: Setup Node.js
            #   uses: actions/setup-node@v4
            #   with:
            #       node-version: "20"

            - name: Lint with ESLint
              run: pnpm lint

    deploy:
        # needs: [build, test, check, lint]
        needs: [build, check, lint]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            # - name: Setup Node.js
            #   uses: actions/setup-node@v4
            #   with:
            #       node-version: "20"

            - name: Deploy to Vercel
              run: |
                  # Your deployment commands here
                  echo "Deploying to Vercel"
