name: Test, Check & Lint

on:
    workflow_call:

jobs:
    # test:
    #     runs-on: ubuntu-latest

    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v4

    # - name: Setup
    #   uses: ./.github/setup

    #         - name: Test
    #           run: pnpm test

    # todo add saving report

    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/setup

            - name: Check TypeScript
              run: pnpm check

    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/setup

            - name: Lint with ESLint
              run: pnpm lint

    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/setup

            - name: Check the styling with Prettier
              run: pnpm prettier
