name: Runs Checks

on:
    push:
        branches:
            - main
        paths:
            - "src/**"
            - "drizzle/**"
            - "pnpm-lock.yaml"
    workflow_dispatch:

jobs:
    checks:
        uses: ./.github/workflows/checks-template.yaml
