name: Typescript check

on:
    workflow_dispatch:
    workflow_call:

jobs:
    install:
        uses: ./.github/workflows/install.yaml
    check:
        runs-on: ubuntu-latest
        needs: install

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/setup

            # - name: Setup Node.js
            #   uses: actions/setup-node@v4
            #   with:
            #       node-version: "20"

            - name: Check TypeScript
              run: pnpm check
