name: Deploy to production environment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    # todo deploy master and production
    # make deploy template

on:
    workflow_dispatch:

jobs:
    checks:
        uses: ./.github/workflows/checks-template.yaml

    deploy:
        runs-on: ubuntu-latest
        needs: checks
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/setup

            # - name: Install Vercel CLI
            #   run: pnpm install --global vercel@latest

            # - name: Pull Vercel Environment Information
            #   run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            # - name: Build Project Artifacts
            #   run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            # - name: Deploy Project Artifacts to Vercel
            #   run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
