name: Deploy to production environment

on:
    workflow_dispatch:

jobs:
    checks:
        uses: ./.github/workflows/checks.yaml

    deploy:
        runs-on: ubuntu-latest
        needs: checks
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/setup

            # - name: Install Vercel CLI
            #   run: pnpm install --global vercel@latest

            # - name: Pull Vercel Environment Information
            #   run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            # - name: Build Project Artifacts
            #   run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

            # - name: Deploy Project Artifacts to Vercel
            #   run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
