name: Deploy Production

# todo deploy master and production
# make deploy template
# make google login work or some other way to login in branches
# add build back to the checks

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    DATABASE_URL: ${{ secrets.DATABASE_URL }}

on:
    workflow_dispatch:

jobs:
    environment:
        runs-on: ubuntu-latest
        name: Environment
        environment: production
        steps:
            - name: Environment
              run: echo "Production environment"

    checks:
        needs: environment
        uses: ./.github/workflows/checks-template.yaml

    deploy:
        runs-on: ubuntu-latest
        needs: checks
        environment: production
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/setup

            - name: Run Migrations
              run: pnpm run db:migrate

            - name: Install Vercel CLI
              run: pnpm install --global vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ env.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ env.VERCEL_TOKEN }}

            - name: Deploy Production to Vercel
              id: deploy
              run: vercel deploy --prebuilt --prod --token=${{ env.VERCEL_TOKEN }}
