name: Lint check

on:
    workflow_dispatch:
    workflow_call:

jobs:
    install:
        uses: ./.github/workflows/install.yaml
    lint:
        runs-on: ubuntu-latest
        needs: install

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/setup

            - name: Lint with ESLint
              run: pnpm lint
