name: Build, Test, Check & Lint

on:
    push:
        branches:
            - main
        paths:
            - "src/**"
            - "drizzle/**"
            - "pnpm-lock.yaml"
    workflow_dispatch:

jobs:
    checks:
        uses: ./.github/workflows/checks.yaml

    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/setup

            - name: Build
              run: pnpm build:ci
